---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  address: https://hooks.slack.com/services/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
  type: slack
