apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s
  timeout: 60s
  type: oci
  url: oci://ghcr.io/stefanprodan/charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m0s
  url: oci://ghcr.io/stefanprodan/manifests/podinfo
  ref:
    tag: latest
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: podinfo
#   namespace: flux-system
# spec:
#   chart:
#     spec:
#       chart: podinfo
#       reconcileStrategy: ChartVersion
#       sourceRef:
#         kind: HelmRepository
#         name: podinfo
#   interval: 1m0s