apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/SomtochiAma/test-kc
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: testks
  namespace: flux-system
spec:
  force: true
  interval: 60m0s
  timeout: 2m
  path: ./clusters/my-cluster/helm
  prune: true
  suspend: false
  validation: client 
  sourceRef:
    kind: GitRepository
    name: podinfo
    namespace: flux-system
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: podinfo
    namespace: default
  wait: true
  # postBuild:
  #   substitute:
  #     # namespace: "my-namespace"
  #     dd_commit: "bba2c2d53adeed14b838efd256c55c47490bb10e"
  #     dd_tag: "'020220802'"