apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: test-kc
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/SomtochiAma/test-kc
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: testks
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 30s
  path: ./clusters/podinfo
  prune: true
  suspend: false
  validation: client 
  sourceRef:
    kind: GitRepository
    name: test-kc
    namespace: flux-system
  healthChecks:
  - apiVersion: v1
    kind: Pod
    name: nginx
    namespace: default
  images:
  - name: nginx
    newName: my-registry/podinfo
    newTag: v1
  # wait: true
  # postBuild:
  #   substitute:
  #     # namespace: "my-namespace"
  #     dd_commit: "bba2c2d53adeed14b838efd256c55c47490bb10e"
  #     dd_tag: "'020220802'"