---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: Bucket
metadata:
  name: azure-bucket
  namespace: flux-system
spec:
  interval: 1m0s
  provider: azure
  bucketName: testsas
  endpoint: https://testfluxsas.blob.core.windows.net
  # secretRef:
  #   name: azure-sp-auth
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: azure-sp-auth
#   # namespace: flux-system
# type: Opaque
# stringData:
#   sasKey: "?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2022-05-30T15:56:52Z&st=2022-05-30T07:56:52Z&spr=https&sig=%2Ftg1rCbE10aRI%2BrMw695dBEa4xodHCmlI%2BZYogtLsQA%3D"
#   # accountKey: "2gc/GN3e/k9IFS2G2MDpH+dtHZUOIBmia9f1VT7FvZfeOPL3jFDEj8TXrNSVtHVusfJjYdF/pPJzgvAxYfb3/A=="