apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"image.toolkit.fluxcd.io/v1beta1","kind":"ImageRepository","metadata":{"annotations":{"kustomize.toolkit.fluxcd.io/checksum":"bf2bba2f532c9337dec0d87c2a28e1e976986e11"},"labels":{"kustomize.toolkit.fluxcd.io/name":"flux-system","kustomize.toolkit.fluxcd.io/namespace":"flux-system"},"name":"podinfo","namespace":"flux-system"},"spec":{"image":"ghcr.io/stefanprodan/podinfo","interval":"1m0s"}}
    kustomize.toolkit.fluxcd.io/checksum: bf2bba2f532c9337dec0d87c2a28e1e976986e11
  creationTimestamp: "2022-01-18T09:55:36Z"
  generation: 2
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  managedFields:
  - apiVersion: image.toolkit.fluxcd.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:kustomize.toolkit.fluxcd.io/checksum: {}
        f:labels:
          .: {}
          f:kustomize.toolkit.fluxcd.io/name: {}
          f:kustomize.toolkit.fluxcd.io/namespace: {}
      f:spec:
        .: {}
        f:image: {}
        f:interval: {}
    manager: kustomize-controller
    operation: Update
    time: "2022-01-18T10:00:34Z"
  - apiVersion: image.toolkit.fluxcd.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:canonicalImageName: {}
        f:conditions: {}
        f:lastScanResult:
          .: {}
          f:scanTime: {}
          f:tagCount: {}
        f:observedGeneration: {}
    manager: image-reflector-controller
    operation: Update
    time: "2022-01-18T10:00:36Z"
  name: podinfo
  namespace: flux-system
  resourceVersion: "10813"
  uid: be694d99-1ad1-4ad6-ba38-277f4f5c0acc
spec:
  image: ghcr.io/stefanprodan/podinfo
  interval: 1m0s
status:
  canonicalImageName: ghcr.io/stefanprodan/podinfo
  conditions:
  - lastTransitionTime: "2022-01-18T10:00:36Z"
    message: successful scan, found 22 tags
    reason: ReconciliationSucceeded
    status: "True"
    type: Ready
  lastScanResult:
    scanTime: "2022-01-18T10:00:36Z"
    tagCount: 22
  observedGeneration: 2
