apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"image.toolkit.fluxcd.io/v1beta1","kind":"ImageRepository","metadata":{"annotations":{"kustomize.toolkit.fluxcd.io/checksum":"2d4658dcdc25001a71eda88ec9099221fcf93869"},"labels":{"kustomize.toolkit.fluxcd.io/name":"flux-system","kustomize.toolkit.fluxcd.io/namespace":"flux-system"},"name":"podinfo","namespace":"flux-system"},"spec":{"image":"ghcr.io/stefanprodan/podinfo","interval":"1m0s","secretRef":{"name":"regcred"}}}
    kustomize.toolkit.fluxcd.io/checksum: 2d4658dcdc25001a71eda88ec9099221fcf93869
  creationTimestamp: "2022-01-18T09:55:36Z"
  generation: 5
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  managedFields:
  - apiVersion: image.toolkit.fluxcd.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:canonicalImageName: {}
        f:conditions: {}
        f:lastScanResult:
          .: {}
          f:scanTime: {}
          f:tagCount: {}
        f:observedGeneration: {}
    manager: image-reflector-controller
    operation: Update
    time: "2022-01-18T10:00:36Z"
  - apiVersion: image.toolkit.fluxcd.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:kustomize.toolkit.fluxcd.io/checksum: {}
        f:labels:
          .: {}
          f:kustomize.toolkit.fluxcd.io/name: {}
          f:kustomize.toolkit.fluxcd.io/namespace: {}
      f:spec:
        .: {}
        f:image: {}
        f:interval: {}
        f:secretRef:
          .: {}
          f:name: {}
    manager: kustomize-controller
    operation: Update
    time: "2022-01-18T10:02:50Z"
  name: podinfo
  namespace: flux-system
  resourceVersion: "11626"
  uid: be694d99-1ad1-4ad6-ba38-277f4f5c0acc
spec:
  image: ghcr.io/stefanprodan/podinfo
  interval: 1m0s
  secretRef:
    name: regcred
status:
  canonicalImageName: ghcr.io/stefanprodan/podinfo
  conditions:
  - lastTransitionTime: "2022-01-18T10:03:36Z"
    message: auth for "ghcr.io" not found in secret flux-system/regcred
    reason: ReconciliationFailed
    status: "False"
    type: Ready
  lastScanResult:
    scanTime: "2022-01-18T10:02:37Z"
    tagCount: 22
  observedGeneration: 5
