apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
secretGenerator:
  - name: token
    type: kubernetes.io/dockerconfigjson
    options:
      disableNameSuffixHash: true
    files:
    - .dockerconfigjson=creds.json.encrypted