apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
  namespace: flux-system
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 180
  template:
    spec:
      serviceAccountName: kustomize-controller
      containers:
        - name: kubectl
          image: "bitnami/kubectl"
          command:
            - /bin/sh
            - -c
            - |
              sleep 1; if [ "$(kubectl get cm test -n default -o jsonpath={.data.dummy})" = "True" ]; then exit 0; fi; sleep 5; exit 1;
      restartPolicy: Never