apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: frontend-deployer
  namespace: flux-system
spec:
  image: gcr.io/dx-somtoxhi/perl
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: frontend-deployer
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frontend-deployer
  # filterTags:
  #   pattern: "^${tracking_branch}-[a-f0-9]+-(?P<ts>[0-9]+)"
  #   extract: '$ts'
  policy:
    semver:
      range: 1.0.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: frontend-deployer
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: ${branch}
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: ${branch}
  update:
    path: ./ks
    strategy: Setters