---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  force: true
  interval: 60m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: OCIRepository
    name: podinfo
    namespace: flux-system
  targetNamespace: flux-system
  timeout: 30s