apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m0s
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo2
  namespace: flux-system
spec:
  interval: 2m
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/  
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-2
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: GitRepository
        name: podinfo2
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-3
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: GitRepository
        name: podinfo2
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-4
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: GitRepository
        name: podinfo2
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-5
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: GitRepository
        name: podinfo2
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-6
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: GitRepository
        name: podinfo2
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-7
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: GitRepository
        name: podinfo2
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-87
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: GitRepository
        name: podinfo2
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-118
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: GitRepository
        name: podinfo2
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-912
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: GitRepository
        name: podinfo2
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-312
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: GitRepository
        name: podinfo2
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-172
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: GitRepository
        name: podinfo2
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-117
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: GitRepository
        name: podinfo2
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-111
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: GitRepository
        name: podinfo2
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-112
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: GitRepository
        name: podinfo2
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-100
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.x.x'
      sourceRef:
        kind: GitRepository
        name: podinfo2
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 2
---